version: '3'

services:

  whoami:
    image: traefik/whoami
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.dominio.local`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    #   - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    #   - "traefik.http.routers.whoami.service=whoami"
    #   - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    networks:
      - nat

networks:
  default:
    external:
      name: nat